---

- name: Ensure the git repository is cloned
  git:
    repo: "{{ item.value.repo.url }}"
    version: "{{ item.value.repo.version }}"
    dest: "{{ ipmi_exporter_repo_checkout_path }}/{{ item.value.repo.url | basename }}"
  with_dict: "{{ ipmi_exporter_images }}"

- name: Ensure image is built
  docker_image:
    buildargs: "{{ item.value.buildargs | default(omit) }}"
    force: "{{ ipmi_exporter_force_rebuild }}"
    name: "{{ item.value.name }}"
    path: "{{ ipmi_exporter_repo_checkout_path }}/{{ item.value.repo.url | basename }}"
    push: "{{ ipmi_exporter_push }}"
    state: present
  with_dict: "{{ ipmi_exporter_images }}"
