---
- name: Ensure configuration directory exists
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755
  become: true
  with_items:
    - "{{ ipmi_exporter_config_path }}"

- name: Include container config tasks
  include_tasks: update-config.yml
  with_dict: "{{ ipmi_exporter_services }}"
