---
- name: Ensure ipmi_exporter container is stopped
  docker_container:
    name: "{{ item.value.container_name }}"
    state: "absent"
  with_dict: "{{ ipmi_exporter_services }}"

- name: Ensure ipmi_exporter volumes are absent
  docker_volume:
    name: "{{ volume }}"
    with_subelements:
      - "{{ ipmi_exporter_services }}"
      - volumes
