---
- name: Fail if the image is not defined
  fail:
    msg: ipmi_exporter Docker image must be defined via 'ipmi_exporter_image'.
  when: ipmi_exporter_image is none

- include: "{{ ipmi_exporter_action }}.yml"
