---
- name: Pulling ipmi_exporter container image
  docker_image:
    name: "{{ item.value.image }}"
    repository: "{{ item.value.image }}"
    state: present
  with_dict: "{{ ipmi_exporter_services }}"
  when:
    - item.value.enabled
    - ipmi_exporter_action != 'destroy'
