---
- name: Ensure oci-systemd-hook is installed
  yum:
    name: oci-systemd-hook
    state: installed
  become: true

- name: Include tasks to create containers
  include_tasks: create.yml
  with_dict: "{{ ipmi_exporter_services }}"
