---
- name: Converge
  hosts: all
  vars:
    pip_install_packages:
      - name: docker
    ipmi_exporter_image: ipmi_exporter
    ipmi_exporter_devices: []
  pre_tasks:
    - name: install dependencies
      package:
        name: "{{ item }}"
      with_items:
        - git
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - role: stackhpc.ipmi-exporter
      vars:
        ipmi_exporter_action: build
    - role: stackhpc.ipmi_exporter
      vars:
        ipmi_exporter_action: deploy
